[package]
name = "jsonpath_rust_bindings"
version = "0.7.5"
edition = "2021"

[lib]
name = "jsonpath_rust_bindings"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24"
jsonpath-rust = "0.7.5"
serde_json = "1.0"
pythonize = "0.24.0"
